name: Docker-Build-LP-And-Push-To-ECR

on:
  push:
    branches: 
      - test
      
jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Clone my repo
      uses: actions/checkout@v2
    
    - name: Login to Public ECR
      run:  aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k4s3o9y8
 
    - name: Create LP dockerimage
      run: docker build -t landing-lessons .
        
    - name: TAG dockerimage
      run: docker tag landing-lessons:latest public.ecr.aws/k4s3o9y8/landing-lessons:latest
        
    - name: PUSH dockerimage to ECR
      run: docker push public.ecr.aws/k4s3o9y8/landing-lessons:latest
